// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:todo_list/core/env/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Env.webApiKey,
    appId: Env.webAppId,
    messagingSenderId: Env.webMessagingSenderId,
    projectId: Env.webProjectId,
    authDomain: Env.webAuthDomain,
    storageBucket: Env.webStorageBucket,
    measurementId: Env.webMeasurementId,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Env.androidApiKey,
    appId: Env.androidAppId,
    messagingSenderId: Env.androidMessagingSenderId,
    projectId: Env.androidProjectId,
    storageBucket: Env.androidStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.iosApiKey,
    appId: Env.iosAppId,
    messagingSenderId: Env.iosMessagingSenderId,
    projectId: Env.iosProjectId,
    storageBucket: Env.iosStorageBucket,
    iosBundleId: Env.iosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Env.macosApiKey,
    appId: Env.macosAppId,
    messagingSenderId: Env.macosMessagingSenderId,
    projectId: Env.macosProjectId,
    storageBucket: Env.macosStorageBucket,
    iosBundleId: Env.macosBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Env.windowsApiKey,
    appId: Env.windowsAppId,
    messagingSenderId: Env.windowsMessagingSenderId,
    projectId: Env.windowsProjectId,
    authDomain: Env.windowsAuthDomain,
    storageBucket: Env.windowsStorageBucket,
    measurementId: Env.windowsMeasurementId,
  );
}
